[package]
name = "blue"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
camino = "1.1.10"
clap = { version = "4.5.39", features = ["derive"] }
crop = { version = "0.4.3", features = ["graphemes"] }
crossterm = "0.29.0"
pathdiff = { version = "0.2.3", features = ["camino"] }
ratatui = "0.29.0"

[lints]
clippy.pedantic = { level = "warn", priority = -1 }
clippy.redundant_closure = "allow"

# clippy.bool_to_int_with_if = "allow"
# clippy.missing_errors_doc = "allow"
# clippy.missing_panics_doc = "allow"
# clippy.module_name_repetitions = "allow"
# clippy.redundant_closure_for_method_calls = "allow"
# clippy.allow_attributes = "warn"
# clippy.use_self = "warn"
